---
title: "The Magma Blast Flex Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r include=FALSE}
# load packages
library(tidyverse)
library(maps)
library(patchwork)
library(viridis)
library(hrbrthemes)
library(ggplot2)
library(ggthemes)
library(ggridges)
library(tigris)
library(sf)


library(lubridate)
library(broom)
library(knitr)
library(scales)
library(viridis)
library(shiny)
library(leaflet)
library(DT)
library(plotly)
library(flexdashboard)
library(jsonlite)
library(maptools)
library(ggplot2)
library(usmap)
library(scales)
```

```{r include=FALSE}
#Reading in the data
eruptions <- read_csv("../data/eruptions.csv")
events <- read_csv("../data/events.csv")
sulfur <- read_csv("../data/sulfur.csv")
tree_rings <- read_csv("../data/tree_rings.csv")
events <- read_csv("../data/events.csv")
volcano <- read_csv("../data/volcano.csv")
head(eruptions)
```
 
Column {.sidebar}
--------------------------------------------------

Some fun text about why volcano eruptions are great to know about. Yaayyy!!!

Column {data-width=350}
-----------------------------------------------------------------------

### World

```{r}

```

### USA

```{r include=FALSE}

glimpse(volcano)
```

```{r include=FALSE}
# filter US data only
usa_volc <- volcano %>% 
  filter(country == "United States")%>%
  filter(region %in% c( "Canada and Western USA", "Alaska", "Hawaii and Pacific Ocean"))%>%
  mutate(region = factor(region, levels = c("Canada and Western USA", 
                                                      "Alaska", 
                                                      "Hawaii and Pacific Ocean"), 
                      labels = c("Western USA", "Alaska", "Hawaii")))%>%
  mutate(subregion = factor(subregion, levels = c("USA (Washington)", "Aleutian Islands", "Alaska Peninsula", "Alaska (southwestern)", "USA (Oregon)", "USA (Idaho)", "USA (Utah)", "USA (New Mexico)", "USA (California)",  "Alaska (eastern)", "Hawaiian Islands", "Alaska (western)", "USA (Arizona)", "USA (Nevada)", "USA (Wyoming)" ), 
                      labels = c("Washington", "Alaska", "Alaska", "Alaska", "Oregon", "Idaho", "Utah", "New Mexico", "California",  "Alaska", "Hawaii", "Alaska", "Arizona", "California", "Wyoming" )))

head(usa_volc)
  
```
```{r include=FALSE}
usa_volc[64, 9] = -180.42
usa_volc[14, 9] = -184.089
```

```{r include=FALSE}
#Merge eruptions info into volcano data bu volcano number
usa_ve<- full_join(usa_volc, eruptions, by = "volcano_number")

usa_ve<-usa_ve%>%
  drop_na(region)%>%
  select(-latitude.y, -longitude.y, volcano_name.y)%>%
  mutate(latitude=latitude.x)%>%
  mutate(longitude=longitude.x)%>%
  mutate(volcano_name= volcano_name.x)%>%
  select(volcano_number, volcano_name, primary_volcano_type:subregion, elevation:population_within_100_km, eruption_number:longitude)%>%
  dplyr::mutate(subregion = forcats::fct_lump(subregion, n = 5))%>%
  mutate(subregion = fct_reorder(subregion, elevation))

head(usa_ve)
```

	



```{r include=FALSE}
# load map for US
usa <- map_data("world", region = "usa", class = "sf")


```


```{r include=FALSE}
#Change to an sf object by saying which columns are the coordinates and setting a CRS:
usa_crs<- st_as_sf(usa_ve, coords = c("longitude", "latitude")) %>%
  st_set_crs(4269) #setting CRS
usa_crs %>% slice(1:3)
```


```{r include=FALSE}
# ridgeline plot of elevation across regions
p1 <- ggplot() +
  geom_density_ridges_gradient(
    data = usa_ve,
    na.rm = TRUE,
    aes(x = elevation, y = subregion, fill = stat(x))
  ) + #population_within_100_km last_eruption_year
  scale_fill_viridis(name = "Elevation (m)", option = "A") +
  theme_minimal() +
  theme(
    legend.position = "none", 
    panel.grid = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    axis.title.x = element_blank()
  )
p1
```


```{r include=FALSE}
# map of volcano locations, colour coded by elevation
p2 <- ggplot() +
  geom_polygon(
    data = usa,
    aes(x = long, y = lat, group = group),
    fill = "lightgrey",
    alpha = 0.6
  ) +
  xlim(c(-186, -65)) + ylim(c(18, 72))+
  
  geom_point(
    data = usa_ve,
    aes(x = longitude, y = latitude, colour = elevation),
  ) +
  scale_color_viridis(name = "Elevation(m)", option= "magma", limits = c(-750, 5000)) +

  
  theme_void()+
  theme(legend.position = "right")
  
p2

```

```{r include=FALSE}
# specify layout for patchwork  
layout <- c(
  area(0, 0, 5, 5), 
  area(0, 4, 2.5, 5.5)
)
```


```{r message=FALSE, warning=FALSE}
# put it all together
p2 +
  p1 + 
  plot_layout(design = layout) +  
  plot_annotation(
    title = "Volcanoes in The United States",
    subtitle = "Histograms of volcano elevations by top 5 subregions",
    caption = "Data from The Smithsonian Institution"
  ) 

#ggsave(filename = "US_volcanoes.png")

```




Column {data-width=350}
-----------------------------------------------------------------------

### Time Series Plot

```{r}

```

### Interactive Table/Plot

```{r}
##cleaning eruption table
eruptions_clean <- eruptions %>% 
  filter(eruption_category == "Confirmed Eruption" & start_year >= 1700 & 
           evidence_method_dating %in% c("Historical Observations", "Seismicity")) %>% 
  select("volcano_number", "volcano_name", "eruption_number","eruption_category",
         "start_year", "end_year", "evidence_method_dating", "vei") %>% 
  drop_na() %>% group_by(volcano_name) %>% 
  mutate(number_of_events = n(), 
         max_vei = max(vei)) %>% 
  ungroup()
##cleaning volcano table
volcano_clean <- volcano %>% 
  select("population_within_100_km", "longitude", "latitude", 
         "country","region", "volcano_number", "volcano_name", 
         "primary_volcano_type")
##Joining tables based on cleaned eruption table
final_table <- eruptions_clean %>% 
  left_join(volcano_clean, by = "volcano_name") %>% 
  mutate(volcano_name = fct_reorder(volcano_name, number_of_events)) %>% 
  filter(number_of_events > 19) %>% 
  drop_na()
```

```{r the_plot}
final_table %>% 
  ggplot()+
  geom_point(aes(x = start_year, y = volcano_name, size = max_vei))
final_table %>% 
  ggplot()+
  geom_col(aes(x = volcano_name, y = population_within_100_km))+
  coord_flip()
```

