---
title: "The Magma Blast"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---
```{r setup, include=FALSE}
library(flexdashboard)
```

```{r include=FALSE}
# load packages
library(tidyverse)
library(maps)
library(patchwork)
library(viridis)
library(hrbrthemes)
library(ggplot2)
library(ggthemes)
library(ggridges)
library(tigris)
library(sf)
library(lemon)
library(lubridate)
library(broom)
library(knitr)
library(scales)
library(viridis)
library(shiny)
library(leaflet)
library(DT)
library(plotly)
library(flexdashboard)
library(jsonlite)
library(maptools)
library(ggplot2)
library(dplyr)
library(usmap)
library(scales)
```

```{r include=FALSE}
#Reading in the data
eruptions <- read_csv("../data/eruptions.csv")
events <- read_csv("../data/events.csv")
sulfur <- read_csv("../data/sulfur.csv")
tree_rings <- read_csv("../data/tree_rings.csv")
events <- read_csv("../data/events.csv")
volcano <- read_csv("../data/volcano.csv")
c_and_c <- read.csv("../data/continent_and_countries.csv") 
colnames(c_and_c) <- c("country", "continent")
head(eruptions)
```

### VOLCANOES AROUND THE WORLD


---

Interesting Facts About Plot


### MAJOR ERUPTIONS SINCE 1700

```{r}
##cleaning eruption table
eruptions_clean <- eruptions %>% 
  filter(eruption_category == "Confirmed Eruption" & start_year >= 1700 & 
           evidence_method_dating %in% c("Historical Observations", "Seismicity")) %>% 
  select("volcano_number", "volcano_name", "eruption_number","eruption_category",
         "start_year", "end_year", "evidence_method_dating", "vei") %>% 
  drop_na() %>% group_by(volcano_name) %>% 
  mutate(number_of_events = n(), 
         max_vei = max(vei)) %>% 
  ungroup()
##cleaning volcano table
volcano_clean <- volcano %>% 
  select("population_within_100_km", "longitude", "latitude", 
         "country","region", "volcano_number", "volcano_name", 
         "primary_volcano_type")
##Joining tables based on cleaned eruption table
final_table <- eruptions_clean %>% 
  left_join(volcano_clean, by = "volcano_name") %>% 
  full_join(c_and_c, by = "country") %>% 
  mutate(volcano_name = fct_reorder(volcano_name, population_within_100_km),
         population = log10(population_within_100_km+1),
         long_lab = round(longitude, 0),
         long_lab_2 = ifelse(long_lab>0, paste0(long_lab, "N"), paste0(-long_lab, "S"))) %>% 
  filter(number_of_events > 5 & number_of_events < 10) %>% 
  drop_na()
final_table$primary_volcano_type <- str_replace_all(final_table$primary_volcano_type, 
                                                    c("Lava dome(s)" ="Lava dome",
                                                  "Stratovolcano(es)"= "Stratovolcano"))
long_lab_2 <- final_table$long_lab_2
```

```{r the_plot}
##Point Plot
left <- final_table %>% 
  ggplot()+
  geom_point(aes(x = start_year, y = volcano_name, size = vei, 
                 color = continent), alpha = 0.7, stroke=1.2)+
  scale_size_area(breaks=c(1,2,3,4,5,6), max_size = 15,name = "Volcano \nExplosivity \nIndex")+
  scale_color_brewer(palette="Dark2", name = "Location (Continent)")+
  scale_x_continuous(breaks=seq(1700, 2020, 40)) +
  scale_y_discrete(expand=c(0.025,0.025))+
  labs(x='', y='')+
  theme_get()+
  guides(color = guide_legend(override.aes = list(size = 20)))+
  theme(legend.position = 'bottom', 
        legend.key = element_blank(),
        legend.text = element_text(size=20),
        legend.title = element_text(face="bold", colour = "black"),
        panel.grid.major.y = element_line(colour= 'black'),
        panel.grid.major.x = element_line(colour = "white"),
        panel.border = element_blank(),
        axis.text = element_text(size=20, colour='black'),
        title = element_text(colour='black', size=30, face='bold', hjust=0),
        plot.subtitle = element_text(colour='white', size=20, face='bold', hjust=0),
        plot.background = element_rect(color='white',fill = "white"),
        panel.background = element_rect(fill = "white",
                                        colour = "white",
                                        linewidth = 5, linetype = "solid"),
        plot.margin=unit(c(0.5, 0.2, 0, 0), 'cm'))+
  ggtitle("Major Eruptions since 1700")
```

```{r plot_2}
##Bar Chart
right <- final_table %>% 
  group_by(volcano_name, population, primary_volcano_type, country, long_lab_2) %>% 
  summarise(count= n()) %>% 
  ungroup() %>% 
  ggplot()+
  geom_col(aes(x = volcano_name, y = population, 
               fill = primary_volcano_type))+
  geom_text(aes(x = volcano_name, y = population, label = country), size = 6,
            hjust = -0.2, color = "black")+
  scale_fill_discrete(name = "Volcano Type")+
  theme_get()+
  guides(fill=guide_legend(ncol=3, override.aes = list(size = 13)))+
  theme(legend.position = "bottom",
        legend.text = element_text(size=20),
        legend.key = element_blank(),
        axis.text.y = element_text(size=20, colour='black', hjust=0.5),
        axis.text.x = element_text(size=20, colour='black'),
        axis.line.x = element_line(color='black'),
        plot.background = element_rect(color='white', fill = "white"),
        title = element_text(colour='black', size=30, face='bold', hjust=0),
        panel.border = element_blank(),
        plot.subtitle = element_text(colour='white', size=20, face='bold', hjust=0),
        panel.background = element_rect(fill = "white",
                                    colour = "white",
                                    linewidth = 0.5, linetype = "solid"),
        plot.margin=unit(c(0.5, 1, 0.2, -0.5), 'cm'))+
  coord_flip()+
  labs(x='', y='Population within 100km of Volcano')+
  scale_y_continuous(expand = c(0, 0), breaks=seq(0, 10, 2.5)) +
  scale_x_discrete(expand=c(0.025,0.025), label = long_lab_2) +
  ggtitle("Population and Country")
```

```{r fig.dim = c(50, 25)}
cowplot::plot_grid(left, right, rel_widths = c(1, 0.5), nrow=1)

```



---

Interesting Facts About Plot


### VOLCANOES IN USA
```{r include=FALSE}

glimpse(volcano)
```

```{r include=FALSE}
# filter US data only
usa_volc <- volcano %>% 
  filter(country == "United States")%>%
  filter(region %in% c( "Canada and Western USA", "Alaska", "Hawaii and Pacific Ocean"))%>%
  mutate(region = factor(region, levels = c("Canada and Western USA", 
                                                      "Alaska", 
                                                      "Hawaii and Pacific Ocean"), 
                      labels = c("Western USA", "Alaska", "Hawaii")))%>%
  mutate(subregion = factor(subregion, levels = c("USA (Washington)", "Aleutian Islands", "Alaska Peninsula", "Alaska (southwestern)", "USA (Oregon)", "USA (Idaho)", "USA (Utah)", "USA (New Mexico)", "USA (California)",  "Alaska (eastern)", "Hawaiian Islands", "Alaska (western)", "USA (Arizona)", "USA (Nevada)", "USA (Wyoming)" ), 
                      labels = c("Washington", "Alaska", "Alaska", "Alaska", "Oregon", "Idaho", "Utah", "New Mexico", "California",  "Alaska", "Hawaii", "Alaska", "Arizona", "California", "Wyoming" )))

head(usa_volc)
  
```
```{r include=FALSE}
usa_volc[64, 9] = -180.42
usa_volc[14, 9] = -184.089
```

```{r include=FALSE}
#Merge eruptions info into volcano data bu volcano number
usa_ve<- full_join(usa_volc, eruptions, by = "volcano_number")

usa_ve<-usa_ve%>%
  drop_na(region)%>%
  select(-latitude.y, -longitude.y, volcano_name.y)%>%
  mutate(latitude=latitude.x)%>%
  mutate(longitude=longitude.x)%>%
  mutate(volcano_name= volcano_name.x)%>%
  select(volcano_number, volcano_name, primary_volcano_type:subregion, elevation:population_within_100_km, eruption_number:longitude)%>%
  dplyr::mutate(subregion = forcats::fct_lump(subregion, n = 5))%>%
  mutate(subregion = fct_reorder(subregion, elevation))

head(usa_ve)
```

	



```{r include=FALSE}
# load map for US
usa <- map_data("world", region = "usa", class = "sf")


```


```{r include=FALSE}
#Change to an sf object by saying which columns are the coordinates and setting a CRS:
usa_crs<- st_as_sf(usa_ve, coords = c("longitude", "latitude")) %>%
  st_set_crs(4269) #setting CRS
usa_crs %>% slice(1:3)
```


```{r include=FALSE}
# ridgeline plot of elevation across regions
p1 <- ggplot() +
  geom_density_ridges_gradient(
    data = usa_ve,
    na.rm = TRUE,
    aes(x = elevation, y = subregion, fill = stat(x))
  ) + #population_within_100_km last_eruption_year
  scale_fill_viridis(name = "Elevation (m)", option = "A") +
  theme_minimal() +
  theme(
    legend.position = "none", 
    panel.grid = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    axis.title.x = element_blank()
  )
p1
```


```{r include=FALSE}
# map of volcano locations, colour coded by elevation
p2 <- ggplot() +
  geom_polygon(
    data = usa,
    aes(x = long, y = lat, group = group),
    fill = "lightgrey",
    alpha = 0.6
  ) +
  xlim(c(-186, -65)) + ylim(c(18, 72))+
  
  geom_point(
    data = usa_ve,
    aes(x = longitude, y = latitude, colour = elevation),
  ) +
  scale_color_viridis(name = "Elevation(m)", option= "magma", limits = c(-750, 5000)) +

  
  theme_void()+
  theme(legend.position = "right")
  
p2

```

```{r include=FALSE}
# specify layout for patchwork  
layout <- c(
  area(0, 0, 5, 5), 
  area(0, 4, 2.5, 5.5)
)
```


```{r message=FALSE, warning=FALSE}
# put it all together
p2 +
  p1 + 
  plot_layout(design = layout) +  
  plot_annotation(
    title = "Volcanoes in The United States",
    subtitle = "Histograms of volcano elevations by top 5 subregions",
    caption = "Data from The Smithsonian Institution"
  ) 

#ggsave(filename = "US_volcanoes.png")

```


---

Interesting Facts About Plot


### TIME SERIES PLOT



---


Interesting Facts About Plot